name: API CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - api/**
      - .github/workflows/api.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - api/**
      - .github/workflows/api.yml

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy api to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.API_APP_NAME}}
          heroku_email: ${{secrets.EMAIL}}
          appdir: "api"
          usedocker: true

